Display sampler metadata when available
astei/spark-ignition pull request #4
Opened 2020-06-08 11:00 UTC by md678685

*Warning: potentially horrible React code ahead*

This is the spark-ignition counterpart to lucko/spark#58 and lucko/spark-web#4 (showing platform metadata) and also somewhat touches #1 (user/time/interval metadata).

Things to consider:
- I have no idea whether this is competent React or JSX code
- Should this be split into another "component" that can be reused in the heap summary (when implemented)?
- I haven't added any CSS for this yet. IMO it looks fine as-is, but spark-web has this metadata inside a box, and lucko/spark-web#4 makes the box expandable (hides platform by default)

Any criticism welcomed (first time doing React stuff)

2020-06-08 17:04 UTC, astei requested changes
Not bad for a beginner to React

2020-06-08 17:04 UTC, astei commented on src/types/Sampler.js
> +    console.log(metadata)
Remove this debug code.

2020-06-08 17:04 UTC, astei commented on src/types/Sampler.js
> +        if (type === 1) {
Not a fan of the magic value going on here.

2020-06-08 17:04 UTC, astei commented on src/types/Sampler.js
> +    let userData
This logic can be extracted into it's own component to make this a bit neater

2020-06-08 17:04 UTC, astei commented on src/types/Sampler.js
> +    if (metadata.platform) {
Ditto

2020-06-09 13:30 UTC, md678685 commented
I've updated this PR according to review comments.

Currently `CommonMetadata` actually depends on metadata that is specific to the sampler output and is missing from heapdump outputs, which matches how spark-web does this. `PlatformMetadata` can be reused for the heapdump when implemented, but spark-web doesn't currently show any metadata for heapdumps and spark-ignition doesn't support heapdumps, so I'm not sure whether this is worth considering right now.

2020-06-26 01:40 UTC, astei approved these changes

2020-06-29 13:41 UTC, md678685 commented
This is ready for merge whenever you're happy to merge it.

2020-09-05 19:15 UTC, merged